apiVersion: nvidia.com/v1alpha1
kind: GPUCluster
metadata:
  name: gpu-cluster
spec:
  draDriver:
    repository: nvcr.io/nvidia
    image: dra-driver-nvidia-gpu
    version: v0.5.0
    imagePullPolicy: IfNotPresent
    computeDomains:
      enabled: false
  dcgm:
    enabled: false
  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 15s
  hostPaths:
    driverInstallDir: /run/nvidia/driver
    kubeletRootDir: /var/lib/kubelet
