apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "true"
