apiVersion: nvidia.com/v1alpha1
kind: NVIDIADriver
metadata:
  name: gpu-driver
spec:
  driverType: gpu
  repository: nvcr.io/nvidia
  image: driver
  version: "595.91.07"
  kernelModuleType: auto
  imagePullPolicy: IfNotPresent
